### ISSUE TITLE
structure improvements

### ISSUE THREAD

**Issue by skewballfox** [secretsauceai/wakeword-data-collector#1]
mostly the same as the related [issue from wakeword-model-maker](https://github.com/secretsauceai/precise-wakeword-model-maker/issues/9). move everything to src, have an out directory, make it easy for people unfamiliar with the project to get their bearings.

**Comment by secretsauceai** [comment]
@skewballfox as this issue doesn't have a DoD (Definition of Done), I have the following question:
Would the PR from @Robin-St meet the criteria to close this issue? If not, I would suggest we open a new issue that has a more tightly defined scope and DoD and then close this issue and cross-link it to the new one. What do you think? 

@Robin-St, I would also be curious to your input on this project. Perhaps we could also discuss on the Secret Sauce AI slack about this? Here is a link to our slack: https://join.slack.com/t/secretsauceorg/shared_invite/zt-1mfrofp2t-A0lGf6w8Vv~_iiTK_qka2w

**Comment by skewballfox** [comment]
> as this issue doesn't have a DoD (Definition of Done), I have the following question:
Would the PR from @Robin-St meet the criteria to close this issue? 

I took a look at the contents of #7 , and the structure in that PR follows the convention for python applications. I'll go ahead and close this
